package com.esotericsoftware.reflectasm;

import java.lang.invoke.MethodHandle;

/**
 * A wrapper for a {@link MethodHandle}.
 * These Wrappers are generated by the {@link WrapperFactory}.
 */
public abstract class HandleWrapper<T> {
    /** {@link MethodHandle#invoke(Object...)}. */
    public abstract Object invoke(T instance, Object... args) throws Throwable;
}
